// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// newPredictPolywogC
List newPredictPolywogC(NumericMatrix X, IntegerMatrix poly_terms, List coef, bool avg, bool interval, double level);
RcppExport SEXP polywog_newPredictPolywogC(SEXP XSEXP, SEXP poly_termsSEXP, SEXP coefSEXP, SEXP avgSEXP, SEXP intervalSEXP, SEXP levelSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP );
        Rcpp::traits::input_parameter< IntegerMatrix >::type poly_terms(poly_termsSEXP );
        Rcpp::traits::input_parameter< List >::type coef(coefSEXP );
        Rcpp::traits::input_parameter< bool >::type avg(avgSEXP );
        Rcpp::traits::input_parameter< bool >::type interval(intervalSEXP );
        Rcpp::traits::input_parameter< double >::type level(levelSEXP );
        List __result = newPredictPolywogC(X, poly_terms, coef, avg, interval, level);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
