# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computePredict <- function(X, poly_terms, coef, forPredVals, interval, bag, level) {
    .Call('polywog_computePredict', PACKAGE = 'polywog', X, poly_terms, coef, forPredVals, interval, bag, level)
}

