# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeExpandMatrix <- function(X, poly_terms) {
    .Call('_polywog_computeExpandMatrix', PACKAGE = 'polywog', X, poly_terms)
}

computeMargEff <- function(X, poly_terms, coef, coef_is_zero, xvar_col) {
    .Call('_polywog_computeMargEff', PACKAGE = 'polywog', X, poly_terms, coef, coef_is_zero, xvar_col)
}

computePolyTerms <- function(degree, k_expand, k_lin) {
    .Call('_polywog_computePolyTerms', PACKAGE = 'polywog', degree, k_expand, k_lin)
}

computePredict <- function(X, poly_terms, coef, forPredVals, interval, bag, level, transform = FALSE) {
    .Call('_polywog_computePredict', PACKAGE = 'polywog', X, poly_terms, coef, forPredVals, interval, bag, level, transform)
}

